<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_21 Des 2022 (13.29) - 20 Jan 2023 (13.2_3ee283</name>
   <tag></tag>
   <elementGuidId>e19ac1d6-41e7-48bb-9b9e-69ef1eaa0033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd38e2a9-4d1f-44af-8d34-dea371fc9823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative rounded-20 border bg-white py-4 shadow-4</value>
      <webElementGuid>41499f49-5e5a-4ec9-94ef-2da983835dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21 Des 2022 (13.29) - 20 Jan 2023 (13.29)PENDINGZumba Updated BarengZumbaRp 180.000Angelinee Feliciaaangel.geumyoil@gmai...Active</value>
      <webElementGuid>3e8b66d9-8921-4040-a52e-a542d6bcaa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-2 2xl:grid-cols-3&quot;]/div[3]/div[@class=&quot;relative rounded-20 border bg-white py-4 shadow-4&quot;]</value>
      <webElementGuid>06b9aeea-9bc7-42a8-875a-f8223caa3ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e23f8122-7c32-4916-9a3f-5d3bbd519084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative rounded-20 border bg-white py-4 shadow-4</value>
      <webElementGuid>6e334ca6-1670-41c4-9077-f7a5dea48568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21 Des 2022 (13.29) - 20 Jan 2023 (13.29)PENDINGZumba Updated BarengZumbaRp 180.000Angelinee Feliciaaangel.geumyoil@gmai...Active</value>
      <webElementGuid>2c64e836-c3d1-42f6-823e-307b976a995a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-2 2xl:grid-cols-3&quot;]/div[3]/div[@class=&quot;relative rounded-20 border bg-white py-4 shadow-4&quot;]</value>
      <webElementGuid>30866611-43b8-4c56-a644-5bcbc780c7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>2c0bd634-8b0f-41d3-ab5b-0a7c1ea4b384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::div[2]</value>
      <webElementGuid>d2cd306e-297b-4345-9a0b-748388ca8093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara menyehatkan ba...'])[1]/following::div[14]</value>
      <webElementGuid>35504c22-1847-4ab1-93c4-8e8b197f98bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>db6a0f82-3992-4481-be40-fb18cd823c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '21 Des 2022 (13.29) - 20 Jan 2023 (13.29)PENDINGZumba Updated BarengZumbaRp 180.000Angelinee Feliciaaangel.geumyoil@gmai...Active' or . = '21 Des 2022 (13.29) - 20 Jan 2023 (13.29)PENDINGZumba Updated BarengZumbaRp 180.000Angelinee Feliciaaangel.geumyoil@gmai...Active')]</value>
      <webElementGuid>ce8e1380-28e6-4f86-b442-628280d4c055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
