<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sit Up_fi fi-rr-menu-dots-vertical</name>
   <tag></tag>
   <elementGuidId>5e29060a-a818-435f-bfa1-76076d8f3d9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fi.fi-rr-menu-dots-vertical</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bf04bc1e-98c3-441e-be73-3d263d9db327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi fi-rr-menu-dots-vertical</value>
      <webElementGuid>9ae52ea5-5614-4d7c-a794-ad82d8b026c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[1]/div[@class=&quot;h-full rounded-20 bg-white shadow-4&quot;]/div[@class=&quot;relative overflow-hidden pb-48&quot;]/div[@class=&quot;group relative&quot;]/button[@class=&quot;absolute right-0 top-0 cursor-pointer rounded-bl-xl rounded-tr-20 bg-neutral-60 bg-opacity-60 px-4 py-2 text-blue-100 shadow-4&quot;]/i[@class=&quot;fi fi-rr-menu-dots-vertical&quot;]</value>
      <webElementGuid>5a381535-5187-45c4-8328-732b2f99fbc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/button/i</value>
      <webElementGuid>89891c75-6497-410e-9c87-e6e445fb422e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div[2]/button/i</value>
      <webElementGuid>a5f1d068-78f1-4e68-883b-6bbcf8c58c9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
