<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_21 Des 2022 (21.21) - 20 Jan 2023 (21.2_88f6e6</name>
   <tag></tag>
   <elementGuidId>8eb2d166-4bd2-46b2-acb6-8e5438633205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[9]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>109d50eb-c008-4e63-8187-b47b7553e5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative h-full rounded-20 border bg-white py-4 shadow-4</value>
      <webElementGuid>7e7e1e56-51e4-46b1-be7a-8e172baac968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21 Des 2022 (21.21) - 20 Jan 2023 (21.21)PENDINGYogaActiveSuriptoRp 155.500Angeline Oneangelinefelicia.has...Sunday (09:00 - 11:00); Wednesday (13:00 - 15:00); </value>
      <webElementGuid>b72c232f-9f16-4ff5-a29b-dfd4acc97364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-2 2xl:grid-cols-3&quot;]/div[9]/div[@class=&quot;relative h-full rounded-20 border bg-white py-4 shadow-4&quot;]</value>
      <webElementGuid>11b0b02f-0917-449e-a365-d1565dbd69c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58c18143-77ea-43b6-b770-befee0ba27b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative h-full rounded-20 border bg-white py-4 shadow-4</value>
      <webElementGuid>4492ce43-d541-4834-896d-0199a77bf55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21 Des 2022 (21.21) - 20 Jan 2023 (21.21)PENDINGYogaActiveSuriptoRp 155.500Angeline Oneangelinefelicia.has...Sunday (09:00 - 11:00); Wednesday (13:00 - 15:00); </value>
      <webElementGuid>1008030b-3483-4038-aee2-4b4d51cee26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-2 2xl:grid-cols-3&quot;]/div[9]/div[@class=&quot;relative h-full rounded-20 border bg-white py-4 shadow-4&quot;]</value>
      <webElementGuid>2e822e54-27e9-4a47-b2a4-a0f654bb2c13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[9]/div</value>
      <webElementGuid>686843cb-8044-441e-812d-b084f7cc7083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[8]/following::div[14]</value>
      <webElementGuid>72af5fe1-3a8a-4ee0-99f2-1a4d49f984f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zumba'])[7]/following::div[14]</value>
      <webElementGuid>69d504d2-515c-484d-9a66-bb457065bd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div</value>
      <webElementGuid>5491f274-af40-4d7b-a080-525535a38b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '21 Des 2022 (21.21) - 20 Jan 2023 (21.21)PENDINGYogaActiveSuriptoRp 155.500Angeline Oneangelinefelicia.has...Sunday (09:00 - 11:00); Wednesday (13:00 - 15:00); ' or . = '21 Des 2022 (21.21) - 20 Jan 2023 (21.21)PENDINGYogaActiveSuriptoRp 155.500Angeline Oneangelinefelicia.has...Sunday (09:00 - 11:00); Wednesday (13:00 - 15:00); ')]</value>
      <webElementGuid>7f1d9f84-9d7a-446f-9f7b-b3541aeff294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
