<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>0ef8494e-ac8e-4eca-997a-40eccec41935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>1143d2c6-871b-445c-9172-df64067b4394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/clean-code-72e8f.appspot.com/contents-videos/45cef3f06ce946b695cf33d568a76ac0.mp4?Expires=1703155695&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=I42ZlV%2FZhQudVuiVPiEPZXZBGcEWlLKkA2p47ZVh66jr2o0vRUyIputLGhSEbyKvksSHnFNgpuLAAd+D7jfFgiIRQuYbrjYxdnzHs9%2FgUmOk66ZhMqU5UisMDIxGkogQ1jlQXY+bikxAVVhhoU+lAChMo68M4QBguH4tOTleSPtSHcBxhYnzjS2d6OOvvveZ6a0GYb3buCwJzeeN6XStTGaw5KZl%2Fm6XbWP64Z8sAecmqAzzVWwXitCC0U2qLUm+aHL%2FwaU70n%2FFVMeg3p34j9cZuvUOBx2E8qr6LGwyt08QV8%2FfnPd59a0t5a3vE5BV4jBjaKFmgAU1MYkXgcigbQ%3D%3D</value>
      <webElementGuid>f7d09b27-b68f-4a4f-9f9d-de18d0ed7668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f98a0a43-d2ed-431c-8279-ae8d6966738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-20 pb-4 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[1]/div[@class=&quot;h-full rounded-20 bg-white shadow-4&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-48&quot;]/div[@class=&quot;player-wrapper&quot;]/div[@class=&quot;video-player&quot;]/video[1]</value>
      <webElementGuid>3ee4ac54-7a47-4855-a9d3-87f06841a545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/video</value>
      <webElementGuid>66726cb7-912f-497d-a28b-40c92d98ea09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>96ec6cb0-a860-4264-8610-fe6199688272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://storage.googleapis.com/clean-code-72e8f.appspot.com/contents-videos/45cef3f06ce946b695cf33d568a76ac0.mp4?Expires=1703155695&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=I42ZlV%2FZhQudVuiVPiEPZXZBGcEWlLKkA2p47ZVh66jr2o0vRUyIputLGhSEbyKvksSHnFNgpuLAAd+D7jfFgiIRQuYbrjYxdnzHs9%2FgUmOk66ZhMqU5UisMDIxGkogQ1jlQXY+bikxAVVhhoU+lAChMo68M4QBguH4tOTleSPtSHcBxhYnzjS2d6OOvvveZ6a0GYb3buCwJzeeN6XStTGaw5KZl%2Fm6XbWP64Z8sAecmqAzzVWwXitCC0U2qLUm+aHL%2FwaU70n%2FFVMeg3p34j9cZuvUOBx2E8qr6LGwyt08QV8%2FfnPd59a0t5a3vE5BV4jBjaKFmgAU1MYkXgcigbQ%3D%3D']</value>
      <webElementGuid>ad1f511f-fdae-43e6-b6e6-c65522b0e3fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
